### ISSUE TITLE
Post Match screen saying horizontal

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/lovat-collection#22]

**Comment by CassieColby** [comment]
There's also occasionally  the issue where the in match game screen stays in vertical.

**Comment by MangoSwirl** [comment]
Have we tested this enough to consider it fixed?

**Comment by CassieColby** [comment]
I thought so, but I will do more today

**Comment by MangoSwirl** [comment]
Temporary fix in place, revisit later.
